#pragma once
#include <Arduino.h>

#define DEVICE_NAME "Soil Moisture"

#define STATE_UPDATE_INTERVAL 5000
#define HEARTBEAT_INTERVAL 60000

#define SOIL_ADC_PIN A0
#define SOIL_CFG_BUTTON_PIN 0
#define LED_PIN 2

#define LED_BLINK_SEND_MS 100

#define ESPNOW_CHANNEL 1
#define ESPNOW_PAIR_INTERVAL_MS 3000
#define ESPNOW_MAX_PAIR_ATTEMPTS 10
#define ESPNOW_PAIR_TIMEOUT_MS 30000

#define WIFI_CONFIG_PORTAL_SSID "ESP8266_SoilMoisture"
#define WIFI_CONFIG_PORTAL_PASS "password123"
#define WIFI_CONFIG_PORTAL_TIMEOUT_S 120
#define WIFI_CONNECT_TIMEOUT_MS 5000

#define DEEP_SLEEP_INTERVAL_DEFAULT 600
#define DEEP_SLEEP_INTERVAL_MIN 60
#define DEEP_SLEEP_INTERVAL_MAX 3600
