[platformio]
default_envs = esp8266

[env]
build_flags = -Wall -std=gnu++17
monitor_speed = 115200
lib_ldf_mode = deep
lib_extra_dirs =
    ../../shared
lib_deps =
    bblanchon/ArduinoJson @ ^7
    file://../../wifimanager
    Aircoookie/Espalexa @ ^2.7.0

[env:esp8266]
platform = espressif8266
board = d1_mini
framework = arduino
lib_extra_dirs = ../../shared
board_build.f_cpu = 80000000L
board_build.flash_mode = dout
board_build.ldscript = eagle.flash.4m1m.ld
build_flags =
    ${env.build_flags}
    -DREPEATER_ENABLED
    -DALEXA_ENABLED
    -DPINS_ENABLED
    -DESPNOW_ENABLED
    -DWIFI_CHANNEL=4

[env:esp8266_ota]
platform = espressif8266
board = d1_mini
framework = arduino
lib_extra_dirs = ../../shared
board_build.f_cpu = 80000000L
board_build.flash_mode = dout
board_build.ldscript = eagle.flash.4m1m.ld
build_flags =
    ${env.build_flags}

    -DREPEATER_ENABLED
    -DALEXA_ENABLED
    ;-DTCP_ENABLED
    -DPINS_ENABLED
    -DSTATIC_WIFI
    -DPINS_ENABLED
    -DESPNOW_ENABLED
    -DWIFI_SSID=\"micasa\"
    -DWIFI_PASS=\"3938373635\"
    -DWIFI_CHANNEL=1
    -DWIFI2_SSID=\"kcasa\"
    -DWIFI2_PASS=\"3938373635\"
    -DWIFI2_CHANNEL=1

lib_deps =
    ${env.lib_deps}
upload_protocol = espota
upload_port = 192.168.1.118
upload_flags =
    --port=8266
    --auth=

[env:lamp_alexa]
platform = espressif8266
board = d1_mini
framework = arduino
lib_extra_dirs = ../../shared
lib_ldf_mode = chain+
board_build.f_cpu = 80000000L
board_build.flash_mode = dout
board_build.ldscript = eagle.flash.4m1m.ld
build_flags =
    ${env.build_flags}
    -DPINS_ENABLED
    -DALEXA_ENABLED
    -DTCP_ENABLED
    -DESPALEXA_DEBUG
    -DSTATIC_WIFI
    -DWIFI_SSID=\"micasa\"
    -DWIFI_PASS=\"3938373635\"

[env:esp8266_esp01s]
platform = espressif8266
board = esp01_1m
framework = arduino
lib_extra_dirs = ../../
board_build.f_cpu = 80000000L
board_build.flash_mode = dout
board_build.ldscript = eagle.flash.1m.ld
build_flags =
    ${env.build_flags}
    -I../../shared
    -DESP01S
    -DSTATIC_WIFI
    ;-DPINS_ENABLED
    ;-DREPEATER_ENABLED
    -DWIFI_SSID=\"kcasa\"
    -DWIFI_PASS=\"3938373635\"
    -DGATEWAY_MAC=\"\"

lib_deps =
    bblanchon/ArduinoJson @ ^7

[env:esp8266_tcp]
platform = espressif8266
board = d1_mini
framework = arduino
lib_extra_dirs = ../../shared
board_build.f_cpu = 80000000L
board_build.flash_mode = dout
board_build.ldscript = eagle.flash.4m1m.ld
build_flags =
    ${env.build_flags}
    -DPINS_ENABLED
    -DALEXA_ENABLED
    -DTCP_ENABLED
    -DSTATIC_WIFI
    -DWIFI_SSID=\"kcasa\"
    -DWIFI_PASS=\"3938373635\"
