[env:esp8266_gateway]
platform = espressif8266
board = d1_mini
framework = arduino
monitor_speed = 115200
monitor_filters = esp8266_exception_decoder
build_flags = 
    -D ESP_NOW_CHANNEL=1
    -D MAX_VIRTUAL_SENSORS=20
    -D PAIRING_WINDOW_MS=180000
    -D BRIDGE_DISCOVERY_PORT=5000
    -D HEARTBEAT_INTERVAL_MS=30000
    -D SENSOR_TIMEOUT_MS=300000
    -D PAIR_BUTTON_GPIO=0
    -D STATUS_LED_GPIO=2
lib_deps = 
    bblanchon/ArduinoJson@^7.2.1
    tzapu/WiFiManager@^2.0.17

board_build.flash_mode = dio
board_build.f_cpu = 80000000L
upload_speed = 115200

[env:esp8266_gateway_ota]
platform = espressif8266
board = d1_mini
framework = arduino
board_build.flash_mode = dio
board_build.f_cpu = 80000000L
upload_protocol = espota

upload_port = 192.168.1.52

upload_speed = 115200
monitor_speed = 115200
monitor_filters = esp8266_exception_decoder
build_flags = 
    -D ESP_NOW_CHANNEL=1
    -D MAX_VIRTUAL_SENSORS=20
    -D PAIRING_WINDOW_MS=180000
    -D BRIDGE_DISCOVERY_PORT=5000
    -D HEARTBEAT_INTERVAL_MS=30000
    -D SENSOR_TIMEOUT_MS=300000
    -D PAIR_BUTTON_GPIO=0
    -D STATUS_LED_GPIO=2
lib_deps = 
    bblanchon/ArduinoJson@^7.2.1
    tzapu/WiFiManager@^2.0.17