#pragma once
#include <Arduino.h>

#define FW_VERSION "v0.0.11"
#define DEVICE_NAME "Rain ESP-NOW"

#define STATE_UPDATE_INTERVAL 5000
#define STATE_SEND_THRESHOLD 5
#define STATE_FORCE_INTERVAL 300000
#define HEARTBEAT_INTERVAL 60000
#define TELEMETRY_INTERVAL 30000

#define RAIN_ANALOG_PIN A0
#define RAIN_DIGITAL_PIN 16
#define LED_PIN 2

#define LED_BLINK_WIFI_MS 200
#define LED_BLINK_GATEWAY_MS 2000

#define ESPNOW_CHANNEL 1
#define ESPNOW_SEND_RETRIES 3
#define ESPNOW_ACK_TIMEOUT_MS 200
#define ESPNOW_PAIR_INTERVAL_MS 10000
#define ESPNOW_MAX_PAIR_ATTEMPTS 30

#define WIFI_CONFIG_PORTAL_SSID "ESP8266_Chuva"
#define WIFI_CONFIG_PORTAL_PASS "password123"
