[env:esp8266]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
monitor_filters = esp8266_exception_decoder
build_flags =
    -D ESPNOW_CHANNEL=1
lib_deps =
    bblanchon/ArduinoJson@^7.3.1
    tzapu/WiFiManager@^2.0.0

[env:esp8266_ota]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
upload_protocol = espota
upload_port = 192.168.1.53
build_flags =
    -D ESPNOW_CHANNEL=1
lib_deps =
    bblanchon/ArduinoJson@^7.3.1
    tzapu/WiFiManager@^2.0.0
