#pragma once
#include <Arduino.h>

#define FW_VERSION "v0.0.30"
#define DEVICE_NAME "DHT+Gas"

#define STATE_UPDATE_INTERVAL 5000
#define STATE_SEND_THRESHOLD_TEMP 0.5
#define STATE_SEND_THRESHOLD_HUM 3.0
#define STATE_SEND_THRESHOLD_GAS 5
#define STATE_FORCE_INTERVAL 300000
#define HEARTBEAT_INTERVAL 60000
#define TELEMETRY_INTERVAL 30000

#define DHT_PIN 4
#define DHT_TYPE DHT22
#define GAS_ANALOG_PIN A0
#define GAS_DIGITAL_PIN 16

#define LED_PIN 2
#define GAS_LED_ALERT_PIN 12
#define GAS_LED_ALARM_PIN 5

#define GAS_ALERT_THRESHOLD 15
#define GAS_ALARM_THRESHOLD 30
#define NORMAL_PULSE_MS 500
#define ALARM_BLINK_FAST_MS 200
#define ALARM_BLINK_SLOW_MS 1000
#define LED_BLINK_WIFI_MS 200
#define LED_BLINK_GATEWAY_MS 2000

#define ESPNOW_CHANNEL 1
#define ESPNOW_SEND_RETRIES 3
#define ESPNOW_ACK_TIMEOUT_MS 200
#define ESPNOW_PAIR_INTERVAL_MS 10000
#define ESPNOW_MAX_PAIR_ATTEMPTS 30

#define WIFI_CONFIG_PORTAL_SSID "ESP8266_DHT_Gas"
#define WIFI_CONFIG_PORTAL_PASS "password123"

#define EEPROM_ENABLE_ADDR 60
#define EEPROM_ENABLE_TEMP_OFFSET 0
#define EEPROM_ENABLE_GAS_OFFSET 1

