name: "ESP32 Bridge Python"
version: "0.0.10"
slug: "bridge_python"
description: "ESP32 Bridge clone for Home Assistant with MQTT Discovery"
url: "https://github.com/amarildolacerda/bridge"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
startup: "application"
boot: "auto"
init: false
watchdog: true
map:
  - config:rw
  - addons:rw
host_network: true
ports:
  "80/tcp": 80
  "5000/udp": 5000
ports_description:
  "80/tcp": "HTTP API + Web Dashboard"
  "5000/udp": "UDP Device Discovery"
options:
  mqtt_host: "core-mosquitto"
  mqtt_port: 1883
  mqtt_user: ""
  mqtt_pass: ""
  log_level: "info"
  bridge_ip: ""
schema:
  mqtt_host: "str"
  mqtt_port: "int"
  mqtt_user: "str"
  mqtt_pass: "password"
  log_level: "list(debug|info|warn|error)"
  bridge_ip: "str"
