[platformio]
default_envs = esp8266

[env]
build_flags = -Wall -std=gnu++17
monitor_speed = 115200
lib_deps =
    bblanchon/ArduinoJson @ ^7
    tzapu/WiFiManager @ ^0.16
    Aircoookie/Espalexa @ ^2.7.0

[env:esp8266]
platform = espressif8266
board = d1_mini
framework = arduino
board_build.f_cpu = 80000000L
board_build.flash_mode = dout
board_build.ldscript = eagle.flash.4m1m.ld
lib_deps =
    ${env.lib_deps}

[env:esp8266_ota]
platform = espressif8266
board = d1_mini
framework = arduino
board_build.f_cpu = 80000000L
board_build.flash_mode = dout
board_build.ldscript = eagle.flash.4m1m.ld
lib_deps =  
    ${env.lib_deps}
upload_protocol = espota
upload_port = 192.168.4.1
upload_flags =
    --port=8266
    --auth=
