[platformio]
default_envs = esp8266

[env]
build_flags = -Wall -std=gnu++17 -DESPNOW_ENABLED -DWIFI_CHANNEL=4
monitor_speed = 115200
lib_extra_dirs =
    ../../shared
lib_deps =
    bblanchon/ArduinoJson @ ^7
    tzapu/WiFiManager @ ^0.16
    Aircoookie/Espalexa @ ^2.7.0
    
[env:esp8266]
platform = espressif8266
board = d1_mini
framework = arduino
lib_extra_dirs = ../../
board_build.f_cpu = 80000000L
board_build.flash_mode = dout
board_build.ldscript = eagle.flash.4m1m.ld
lib_deps =
    ${env.lib_deps}
build_flags =
    ${env.build_flags}
    -I../../shared
    -DREPEATER_ENABLED
    -DALEXA_ENABLED    

[env:esp8266_ota]
platform = espressif8266
board = d1_mini
framework = arduino
lib_extra_dirs = ../../
board_build.f_cpu = 80000000L
board_build.flash_mode = dout
board_build.ldscript = eagle.flash.4m1m.ld
lib_deps =  
    ${env.lib_deps}
upload_protocol = espota
upload_port = 192.168.1.15
upload_flags =
    --port=8266
    --auth=
build_flags =
    ${env.build_flags}
    -I../../shared
    -DREPEATER_ENABLED
    -DALEXA_ENABLED    

[env:esp8266_tcp]
platform = espressif8266
board = d1_mini
framework = arduino
lib_extra_dirs = ../../
board_build.f_cpu = 80000000L
board_build.flash_mode = dout
board_build.ldscript = eagle.flash.4m1m.ld
lib_deps =
    ${env.lib_deps}
build_flags =
    -Wall -std=gnu++17 -DTCP_ENABLED
    -I../../shared
    -D STATIC_WIFI
    -DWIFI_SSID=\"kcasa\"
    -DWIFI_PASS=\"3938373635\"

[env:lora_esp32]
platform = espressif32
board = ttgo-lora32-v1
framework = arduino
board_build.f_cpu = 240000000L
lib_extra_dirs = ../../shared
lib_deps =
    bblanchon/ArduinoJson @ ^7
    tzapu/WiFiManager @ ^2.0
    sandeepmistry/LoRa @ ^0.8.0
    adafruit/Adafruit SSD1306 @ ^2.5.7
    adafruit/Adafruit GFX Library @ ^1.11.9
    Aircoookie/Espalexa @ ^2.7.0
build_flags =
    -Wall -std=gnu++17
    -I../../shared
    -DLORA_ENABLED
    -DDISPLAY_TTGO
    -DREPEATER_ENABLED
    -DALEXA_ENABLED
    -DWIFI_CHANNEL=4

[env:lora_esp32_ota]
platform = espressif32
board = ttgo-lora32-v1
framework = arduino
board_build.f_cpu = 240000000L
lib_extra_dirs = ../../shared
lib_deps =
    ${env:lora_esp32.lib_deps}
upload_protocol = espota
upload_port = 192.168.1.18
build_flags =
    -Wall -std=gnu++17
    -I../../shared
    -DLORA_ENABLED
    -DDISPLAY_TTGO
    -DREPEATER_ENABLED
    -DALEXA_ENABLED
    -DSTATIC_WIFI
    -DWIFI_SSID=\"kcasa\"
    -DWIFI_PASS=\"3938373635\"
