#pragma once
#include <Arduino.h>

#define FW_VERSION "v0.0.24"
#define DEVICE_NAME "PIR ESP-NOW"

#define STATE_UPDATE_INTERVAL 5000
#define STATE_FORCE_INTERVAL 300000
#define HEARTBEAT_INTERVAL 60000

#define PIR_PIN 4
#define LED_PIN 2

#define LED_BLINK_WIFI_MS 200
#define LED_BLINK_GATEWAY_MS 2000

#define PIR_HOLD_TIME_MS 30000

#define ESPNOW_CHANNEL 1
#define ESPNOW_SEND_RETRIES 3
#define ESPNOW_ACK_TIMEOUT_MS 200
#define ESPNOW_PAIR_INTERVAL_MS 10000
#define ESPNOW_MAX_PAIR_ATTEMPTS 30

#define WIFI_CONFIG_PORTAL_SSID "ESP8266_PIR"
#define WIFI_CONFIG_PORTAL_PASS "password123"
