#ifndef CONFIG_H
#define CONFIG_H

#include "platform.h"
#include "shared_config.h"

#define DEVICE_NAME PLATFORM_PREFIX "_Gateway"

#define MAX_VIRTUAL_SENSORS 64
#define PAIRING_WINDOW_MS 60000
#define HEARTBEAT_INTERVAL_MS 30000
#define SENSOR_TIMEOUT_MS 300000
#define PAIR_BUTTON_GPIO 0
#define STATUS_LED_GPIO 2
#define LOG_BUFFER_SIZE 50
#define LOG_MSG_MAX 64

#define TIME_SYNC_INTERVAL_MS 300000
#define NTP_RETRY_INTERVAL_MS 1800000

#ifndef MQTT_HOST_DEFAULT
#define MQTT_HOST_DEFAULT "0.0.0.0"
#endif
#ifndef MQTT_PORT_DEFAULT
#define MQTT_PORT_DEFAULT 1883
#endif
#ifndef MQTT_USER_DEFAULT
#define MQTT_USER_DEFAULT ""
#endif
#ifndef MQTT_PASS_DEFAULT
#define MQTT_PASS_DEFAULT ""
#endif
#define EEPROM_SENSOR_BASE 0
#define EEPROM_SENSOR_SIZE 48
#define EEPROM_SENSOR_MAX_SLOTS MAX_VIRTUAL_SENSORS
#define EEPROM_MQTT_HOST_OFFSET (EEPROM_SENSOR_BASE + EEPROM_SENSOR_MAX_SLOTS * EEPROM_SENSOR_SIZE)
#define EEPROM_MQTT_PORT_OFFSET (EEPROM_MQTT_HOST_OFFSET + 64)
#define EEPROM_MQTT_USER_OFFSET (EEPROM_MQTT_PORT_OFFSET + 2)
#define EEPROM_MQTT_PASS_OFFSET (EEPROM_MQTT_USER_OFFSET + 32)

#define EEPROM_WIFI_SSID_OFFSET (EEPROM_MQTT_PASS_OFFSET + 32)
#define EEPROM_WIFI_SSID_SIZE 33
#define EEPROM_WIFI_PASS_OFFSET (EEPROM_WIFI_SSID_OFFSET + EEPROM_WIFI_SSID_SIZE)
#define EEPROM_WIFI_PASS_SIZE 65

#define EEPROM_WIFI_MODE_OFFSET (EEPROM_WIFI_PASS_OFFSET + EEPROM_WIFI_PASS_SIZE)
#define EEPROM_WIFI_MODE_SIZE 1
#define EEPROM_WIFI_IP_OFFSET (EEPROM_WIFI_MODE_OFFSET + EEPROM_WIFI_MODE_SIZE)
#define EEPROM_WIFI_IP_SIZE 16
#define EEPROM_WIFI_GW_OFFSET (EEPROM_WIFI_IP_OFFSET + EEPROM_WIFI_IP_SIZE)
#define EEPROM_WIFI_GW_SIZE 16
#define EEPROM_WIFI_MASK_OFFSET (EEPROM_WIFI_GW_OFFSET + EEPROM_WIFI_GW_SIZE)
#define EEPROM_WIFI_MASK_SIZE 16
#define EEPROM_WIFI_DNS_OFFSET (EEPROM_WIFI_MASK_OFFSET + EEPROM_WIFI_MASK_SIZE)
#define EEPROM_WIFI_DNS_SIZE 16

#define EEPROM_SIZE (EEPROM_WIFI_DNS_OFFSET + EEPROM_WIFI_DNS_SIZE)

#define WIFI_CONFIG_PORTAL_SSID "ESPNOW_Gateway_Setup"
#define WIFI_CONFIG_PORTAL_PASS "password123"

#endif