#ifndef CONFIG_H
#define CONFIG_H

#define FW_VERSION "v0.0.20"
#define DEVICE_NAME "ESP8266_Gateway"

#define ESP_NOW_CHANNEL 1
#define MAX_VIRTUAL_SENSORS 20
#define PAIRING_WINDOW_MS 60000
#define HEARTBEAT_INTERVAL_MS 30000
#define SENSOR_TIMEOUT_MS 300000
#define PAIR_BUTTON_GPIO 0
#define STATUS_LED_GPIO 2

#define MQTT_HOST_DEFAULT "0.0.0.0"
#define MQTT_PORT_DEFAULT 1883

#define EEPROM_SIZE 2048
#define EEPROM_SENSOR_BASE 0
#define EEPROM_SENSOR_SIZE 48
#define EEPROM_MQTT_HOST_OFFSET (EEPROM_SENSOR_BASE + MAX_VIRTUAL_SENSORS * EEPROM_SENSOR_SIZE)
#define EEPROM_MQTT_PORT_OFFSET (EEPROM_MQTT_HOST_OFFSET + 64)
#define EEPROM_MQTT_USER_OFFSET (EEPROM_MQTT_PORT_OFFSET + 2)
#define EEPROM_MQTT_PASS_OFFSET (EEPROM_MQTT_USER_OFFSET + 32)

#define WIFI_CONFIG_PORTAL_SSID "ESP_Gateway_Setup"
#define WIFI_CONFIG_PORTAL_PASS "password123"

#endif